server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
#    url: jdbc:mysql://localhost:3306/sim-management-poc
    url: jdbc:mysql://localhost:3306/sim-management
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    password: azgxjaxwfnkjepth
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


    protocol: smtp
    test-connection: false
    username: mrunalnyaykhor@gmail.com

